---
deployment:
 tasks:
 - export DEPLOYPATH=/home/msgtidau/public_html/
 - /bin/cp farkle.html $DEPLOYPATH
 - /bin/cp -R css $DEPLOYPATH
 - /bin/cp -R fonts $DEPLOYPATH 
 - /bin/cp -R images $DEPLOYPATH 
 - /bin/cp -R js $DEPLOYPATH 